# Generated by Django 5.0.2 on 2024-02-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sementes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Defeito', models.BooleanField(default=False)),
                ('TipoDefeito', models.CharField(choices=[('NA', 'Na'), ('Ardido', 'Ardido'), ('Furado', 'Furado'), ('Quebrado', 'Quebrado'), ('Popped Kernel', 'Poppedkernel')], default='NA', max_length=20)),
                ('IntensidadeDefeito', models.IntegerField(choices=[(0, 'Nao'), (1, 'Leve'), (2, 'Severo')], default=0)),
                ('imagem', models.ImageField(upload_to='sementes/imagens/')),
            ],
        ),
    ]
