# Generated by Django 5.0.2 on 2024-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sementes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sementes',
            old_name='imagem',
            new_name='Imagem',
        ),
        migrations.AddField(
            model_name='sementes',
            name='Classificado',
            field=models.BooleanField(default=False),
        ),
    ]
