# Generated by Django 5.0.2 on 2024-02-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sementes', '0002_rename_imagem_sementes_imagem_sementes_classificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sementes',
            name='id',
        ),
        migrations.AddField(
            model_name='sementes',
            name='Id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
