# Generated by Django 5.0.2 on 2024-02-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sementes', '0003_remove_sementes_id_sementes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sementes',
            name='TipoDefeito',
            field=models.CharField(blank=True, choices=[('N/A', 'Na'), ('Ardido', 'Ardido'), ('Furado', 'Furado'), ('Quebrado', 'Quebrado'), ('Popped Kernel', 'Poppedkernel')], default='N/A', max_length=20, null=True),
        ),
    ]
