# Generated by Django 5.0.2 on 2024-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sementes', '0004_alter_sementes_tipodefeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sementes',
            name='IntensidadeDefeito',
            field=models.IntegerField(blank=True, choices=[(0, 'Nao'), (1, 'Leve'), (2, 'Severo')], default=0, null=True),
        ),
    ]
