# Generated by Django 5.0.2 on 2024-02-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sementes', '0005_alter_sementes_intensidadedefeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sementes',
            name='IntensidadeDefeito',
            field=models.IntegerField(blank=True, choices=[(1, 'Leve'), (2, 'Severo')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sementes',
            name='TipoDefeito',
            field=models.CharField(blank=True, choices=[('Ardido', 'Ardido'), ('Furado', 'Furado'), ('Quebrado', 'Quebrado'), ('Popped Kernel', 'Poppedkernel')], default=None, max_length=20, null=True),
        ),
    ]
